server:
  port: 8082
  servlet:
    context-path: /customer-service

keycloak:
  credentials:
    secret: newClientSecret
  resource: newClient
  auth-server-url: http://localhost:8083/auth/
  realm: getir
  scope: profile
  admin:
    username: admin
    password: admin

logging:
  level:
    root: DEBUG
